### ISSUE TITLE
Fails to build with non-default prefix

### ISSUE THREAD

**Issue by jbeich** [hyprwm/hyprutils#28]
Regressed by 104117aed6dd. Affects [FreeBSD](https://wiki.freebsd.org/WarnerLosh/UsrLocal#Include_paths), other BSDs and maybe even Nix due to using different prefix for each package. To reproduce install pixman outside of `/usr` and `/usr/local` thus not part of default C compiler search path.

```
$ export PKG_CONFIG_PATH=/pixman_prefix/lib/pkgconfig
$ pkg-config --cflags pixman-1
-I/pixman_prefix/include/pixman-1

$ cmake .
$ cmake --build .
[...]
In file included from src/math/Region.cpp:1:
./include/hyprutils/math/Region.hpp:3:10: fatal error: 'pixman-1/pixman.h' file not found
    3 | #include <pixman-1/pixman.h>
      |          ^~~~~~~~~~~~~~~~~~~
```

See also https://gitlab.freedesktop.org/pixman/pixman/-/blob/pixman-0.44.2/meson.build#L605

**Comment by jbeich** [comment]
Oops, not just tests but the main lib as well.

**Comment by vaxerski** [comment]
just gotta revert the commit I guess
